In [0]:
import numpy as np
import itertools
import collections
from sklearn.feature_extraction.text import CountVectorizer

In [0]:
import pandas as pd
import gzip


data=pd.read_json('http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Office_Products_5.json.gz',lines=True)



data

           reviewerID        asin  ... unixReviewTime   reviewTime
0      A32T2H8150OJLU  B00000JBLH  ...     1094169600   09 3, 2004
1      A3MAFS04ZABRGO  B00000JBLH  ...     1197676800  12 15, 2007
2      A1F1A0QQP2XVH5  B00000JBLH  ...     1293840000   01 1, 2011
3       A49R5DBXXQDE5  B00000JBLH  ...     1145404800  04 19, 2006
4      A2XRMQA6PJ5ZJ8  B00000JBLH  ...     1375574400   08 4, 2013
...               ...         ...  ...            ...          ...
53253  A1ODOGXEYECQQ8  B00KYA0RC2  ...     1405555200  07 17, 2014
53254  A2XX2A4OJCDNLZ  B00KYA0RC2  ...     1405296000  07 14, 2014
53255  A3LGT6UZL99IW1  B00KYA0RC2  ...     1405468800  07 16, 2014
53256  A1XJOSJN6FHFO0  B00KYA0RC2  ...     1405814400  07 20, 2014
53257   AAEVGE52KL0DJ  B00KYA0RC2  ...     1404604800   07 6, 2014

[53258 rows x 9 columns]

In [0]:
import re

In [0]:
def start_end(string):
  string=re.sub('[^a-zA-Z]',' ',string)
  string=string.lower()
  list1=re.findall("\w+[Gg]", string)
  list2=re.findall("[Bb]\w+", string)
  return(list(set().union(list1,list2)))

In [0]:
data['rev_txt_bg']=data.reviewText.apply(start_end)
data['summary_bg']=data.summary.apply(start_end)

In [0]:
data.head()

       reviewerID  ...    summary_bg
0  A32T2H8150OJLU  ...        [long]
1  A3MAFS04ZABRGO  ...  [flag, bury]
2  A1F1A0QQP2XVH5  ...    [ble, but]
3   A49R5DBXXQDE5  ...            []
4  A2XRMQA6PJ5ZJ8  ...        [best]

[5 rows x 11 columns]

In [0]:
def notb_notg(string):
  string=string.lower()
  string=re.sub('[^a-zA-Z]',' ',string)
  list1=re.findall(r"\b(?!b)\w+(?<!g)\b",string)
  return list1

In [0]:
data['revtxt_notbg']=data.reviewText.apply(notb_notg)

In [0]:
data['revtxt_notbg'].head()

0    [i, my, first, hp, c, in, about, or, so, and, ...
1    [why, this, review, i, feel, very, obliged, to...
2    [i, have, an, hp, gx, that, has, for, more, th...
3    [i, ve, started, more, finance, stuff, recentl...
4    [for, simple, calculations, and, discounted, c...
Name: revtxt_notbg, dtype: object

In [0]:
data.head()

       reviewerID  ...                                       revtxt_notbg
0  A32T2H8150OJLU  ...  [i, my, first, hp, c, in, about, or, so, and, ...
1  A3MAFS04ZABRGO  ...  [why, this, review, i, feel, very, obliged, to...
2  A1F1A0QQP2XVH5  ...  [i, have, an, hp, gx, that, has, for, more, th...
3   A49R5DBXXQDE5  ...  [i, ve, started, more, finance, stuff, recentl...
4  A2XRMQA6PJ5ZJ8  ...  [for, simple, calculations, and, discounted, c...

[5 rows x 12 columns]